In [4]:
import numpy as np

In [7]:
rev = np.array([[10,12,9],[15,11,13]])

In [8]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [9]:
np.sort(rev)

array([[ 9, 10, 12],
       [11, 13, 15]])

In [10]:
rev.ravel()

array([10, 12,  9, 15, 11, 13])

In [11]:
rev.max()

np.int64(15)

In [13]:
rev.sum(axis=1)

array([31, 39])

In [14]:
rev.sum(axis=0)

array([25, 23, 22])

In [24]:
### Rows = Product Column = region/Country
import numpy as np
q1 = np.array([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])

q2 = np.array([
    [209,231,249],
    [155,192,200],
    [310,340,356]
])

In [27]:
q1 + q2

array([[409, 451, 499],
       [305, 372, 410],
       [610, 670, 716]])

In [28]:
q2-q1

array([[  9,  11,  -1],
       [  5,  12, -10],
       [ 10,  10,  -4]])

In [29]:
(q2-q1)*100/q1

array([[ 4.5       ,  5.        , -0.4       ],
       [ 3.33333333,  6.66666667, -4.76190476],
       [ 3.33333333,  3.03030303, -1.11111111]])

In [30]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [34]:
a[-1,0:2]

array([7, 8])

In [36]:
a[: ,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [37]:
# Customer ID, Name
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

In [44]:
trans=np.hstack((c,d))

In [48]:
x, y = np.hsplit(trans,[3]) 

In [49]:
x

array([['101', 'Mira', '101'],
       ['102', 'Abdul', '102'],
       ['103', 'Andrea', '103']], dtype='<U32')

In [50]:
y

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01']], dtype='<U32')