In [1]:
pwd

'C:\\code\\numpy'

In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
l1 = [1,2,3]
l2 = [5,7,4]

for x,y in zip(l1,l2):
    print(x,y)

1 5
2 7
3 4


In [12]:
import time

size = 100000
n1 = np.arange(size)
n2 = np.arange(size)
n1[:6],n2[:6]


(array([0, 1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4, 5]))

In [21]:
start_time = time.time()
n3 = n1+n2
end_time = time.time()
print("Numpy array took :", end_time-start_time)

Numpy array took : 0.001003265380859375


In [25]:
rev_q1_q2 = np.array([[10,12,9],[15,11,13]])
rev_q1_q2.ndim


2

In [26]:
rev_q1_q2

array([[10, 12,  9],
       [15, 11, 13]])

In [41]:
rev_q1_q2.sort

<function ndarray.sort>